### ISSUE TITLE
Problem when i start the bat file

### ISSUE THREAD

**Issue by bomgdan** [TheFuckingRat/RatPoison#123]
So i really want to play with this cheat since its UD and has more features than charlatano, but when i start it i get this error:

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
        at java.util.Collections$SingletonList.get(Unknown Source)
        at rat.poison.RatPoison.loadSettingsFromFiles(RatPoison.kt:181)
        at rat.poison.RatPoison.loadSettingsFromFiles$default(RatPoison.kt:162)
        at rat.poison.RatPoison.main(RatPoison.kt:49)
        at rat.poison.RatPoison.main(RatPoison.kt)
Press any key to continue . . .

I already set my JAVA_HOME, and idk how to fix this, any help would be appreciated.

**Comment by TheFuckingRat** [comment]
Download the latest from here
