### ISSUE TITLE
Still having the same issue when i start the .bat

### ISSUE THREAD

**Issue by bomgdan** [TheFuckingRat/RatPoison#127]
Ive downloaded the newest from here still the same issue it seems.

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
        at java.util.Collections$SingletonList.get(Unknown Source)
        at rat.poison.RatPoison.loadSettingsFromFiles(RatPoison.kt:181)
        at rat.poison.RatPoison.loadSettingsFromFiles$default(RatPoison.kt:162)
        at rat.poison.RatPoison.main(RatPoison.kt:49)
        at rat.poison.RatPoison.main(RatPoison.kt)
Press any key to continue . . .

**Comment by bomgdan** [comment]
fixed it myself.
