### ISSUE TITLE
unknown issue

### ISSUE THREAD

**Issue by phooooon** [TheFuckingRat/RatPoison#129]
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
        at java.util.Collections$SingletonList.get(Unknown Source)
        at rat.poison.RatPoison.loadSettingsFromFiles(RatPoison.kt:181)
        at rat.poison.RatPoison.loadSettingsFromFiles$default(RatPoison.kt:162)
        at rat.poison.RatPoison.main(RatPoison.kt:49)
        at rat.poison.RatPoison.main(RatPoison.kt)
Press any key to continue . . .

**Comment by TheFuckingRat** [comment]
Download the latest from here

**Comment by phooooon** [comment]
This is 1.4.1

**Comment by TheFuckingRat** [comment]
The issue was with 1.4.1, if you download the latest from here it shouldn't be an issue, I just did, built and launched and it works fine. Unless you're copying your settings folder there shouldnt be an issue. Look for hitsound.mp3 in the settings folder (not in the hitsounds folder) or anything that doesnt end with .kts and delete it.

**Comment by mattbot101** [comment]
I think I got the same error when I tried to just move the settings over, just change the settings to what you want.
