### ISSUE TITLE
Can't start the cheat

### ISSUE THREAD

**Issue by rattedpojzn** [TheFuckingRat/RatPoison#142]
I was able to play yesterday, today it won't start. I'm not sure why, here's the error:

Exception in thread "main" kotlin.KotlinNullPointerException
        at rat.poison.scripts.aim.FlatAimKt.flatAim(FlatAim.kt:7)
        at rat.poison.RatPoison.main(RatPoison.kt:87)
        at rat.poison.RatPoison.main(RatPoison.kt)

Version is 1.4.1 by the way.

**Comment by TheFuckingRat** [comment]
Incorrect value/late initialization issue it seems, shouldn't be happening constantly... but is on an older version so I cant look into it too much. I am closing but if there's similar issues with 1.5 just reply back here.
