### ISSUE TITLE
Minor annoyances

### ISSUE THREAD

**Issue by rattedpojzn** [TheFuckingRat/RatPoison#157]
Using Hotfix 6.

UPDATE: It works fine now for some reason, can't tell you why.
The 'old' chams are back. By that I mean that everyone is glowing white a bit (teammates and me) without the teammate/self alpha or setting affecting it. The previous hotfix I was using (not sure if 1 or 2) didn't have this issue.

![selfcham](https://user-images.githubusercontent.com/53067537/65380666-70c7e400-dccf-11e9-98f4-61323278375e.png)

Ticking 'Override Weapons' can mess with 'Enable Perfect Aim', making the sliders show up when it's not enabled and hiding them when you enable the option.

![override](https://user-images.githubusercontent.com/53067537/65380665-702f4d80-dccf-11e9-954d-7781916da1c4.png)

Last and probably nitpicky. I don't really remember if I was using 'Factor Recoil' for the Deagle override, but shooting will cause your crosshair to move at his legs, chest or outside his body with sometimes even 1 shot. Again, this could be just me, and the obvious thing is not to use the recoil option, but it felt like it was way smoother in earlier versions.

**Comment by rattedpojzn** [comment]
Also, I noticed that the cheat is 'crashing' a lot more. Just did 4 times in one match. Here are the logs:

Exception in thread "DefaultDispatcher-worker-2" java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.util.ArrayList$Itr.next(Unknown Source)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt:331)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt)
        at rat.poison.App.render(RatPoison.kt:304)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:125)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by TheFuckingRat** [comment]
![Chams1](https://user-images.githubusercontent.com/46275653/65384295-47ff1900-dce6-11e9-9aad-7b523a413e0a.png)
Shader detail is the reason for the white tint, hotfix 7 should fix the perfect aim issue and other issues with override weapons. Deagle isn't moving to legs but factor recoil would probably be the reason why. The concurrent modification error should be fixed as well (made some changes and haven't had it since)

**Comment by rattedpojzn** [comment]
Didn't know the shader detail was affecting chams, thanks. It's weird because I didn't change my options, just used the new hotfix, and it was glowing white. Then after a couple of crashes and restarting the cheat, it just kinda worked, no white glow.

**Comment by TheFuckingRat** [comment]
I'm assuming the issues are solved.
