### ISSUE TITLE
Deagle is targeting body even though it's set to target head / overlay disappearing when turning on box and skeleton

### ISSUE THREAD

**Issue by furioushell98** [TheFuckingRat/RatPoison#164]
as in the title, the aim on deagle is targeting body and sometimes the aim goes even to legs when the target is far away, while it's normal for other pistols, this clip can show you the difference between shooting with usp-s / deagle : https://streamable.com/b34ro , i tried v1.5.0 hotfix 7 and it didn't have that problem, the deagle targets head all the time. ty for the work on the cheat btw, especially the triggerbot fix. Almost feels like a premium cheat lol
sorry for the shitty video quality,i didnt have shadow play installed and my monitor resolution is 1280x1024

**Comment by TheFuckingRat** [comment]
Factor recoil is why https://gyazo.com/08eab340ef6201b0540e4e879c4e8a53 depending on the distance either might be more usable, but they should still be semi accurate regardless.

**Comment by furioushell98** [comment]
@TheFuckingRat i see. ty for the answer. Also one more thing, idk if it's only me or not but enemy chams doesn't get updated if you set it to something, then saved your own config, then tried to change it again.

**Comment by furioushell98** [comment]
@TheFuckingRat one more thing, when i enable skeleton and box esp (weapon and name only ) for enemies the overlay and the menu disappear after like 5mins and these lines show up in Ratpoison's cmd window: 

Exception in thread "DefaultDispatcher-worker-1" java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.util.ArrayList$Itr.next(Unknown Source)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt:329)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt)
        at rat.poison.App.render(RatPoison.kt:307)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:128)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by TheFuckingRat** [comment]
https://gyazo.com/0930a2132877dc46cff0ea994685eb28 Doesn't seem to be an issue for me, will look into the box esp issue again.
