### ISSUE TITLE
Crashing on open.

### ISSUE THREAD

**Issue by ghoulkiddoo** [TheFuckingRat/RatPoison#184]
It says this: Exception in thread "DefaultDispatcher-worker-2" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.ExceptionInInitializerError
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:125)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
Caused by: java.lang.ExceptionInInitializerError
        at rat.poison.ui.UIMenu.<init>(UIMenu.kt:46)
        at rat.poison.App.create(RatPoison.kt:214)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:429)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:377)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        ... 6 more
Caused by: java.lang.NumberFormatException: empty String
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:451)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisSlider.update(ATabVisSlider.kt:44)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisSlider.<init>(ATabVisSlider.kt:26)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisSlider.<init>(ATabVisSlider.kt:13)
        at rat.poison.ui.uiHelpers.tables.AimBTrigTable.<init>(AimBTrigTable.kt:23)
        at rat.poison.ui.tabs.AimTab.<init>(AimTab.kt:24)
        at rat.poison.ui.UIMenuKt.<clinit>(UIMenu.kt:13)
        ... 12 more

**Comment by TheFuckingRat** [comment]
If this isn't with default settings give a .zip of them

**Comment by ghoulkiddoo** [comment]
Im not too sure if you wanted the CFG settings, or the settings folder. Here's both.

[CFGS.zip](https://github.com/TheFuckingRat/RatPoison/files/3698723/CFGS.zip)
[settings.zip](https://github.com/TheFuckingRat/RatPoison/files/3698725/settings.zip)

**Comment by TheFuckingRat** [comment]
Half of your BoneTrigger.txt file is deleted, copy/paste https://github.com/TheFuckingRat/RatPoison/blob/master/settings/BoneTrigger.txt to that file.

**Comment by ghoulkiddoo** [comment]
Thank you, fixed it all up.
