### ISSUE TITLE
Overlay not working

### ISSUE THREAD

**Issue by italycross** [TheFuckingRat/RatPoison#188]
I got this problem when I run with overlay

Exception in thread "DefaultDispatcher-worker-1" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.ExceptionInInitializerError
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:125)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
Caused by: java.lang.ExceptionInInitializerError
        at rat.poison.ui.tabs.VisualsTab.<init>(VisualsTab.kt:44)
        at rat.poison.ui.UIMenuKt.<clinit>(UIMenu.kt:14)
        at rat.poison.ui.UIMenu.<init>(UIMenu.kt:46)
        at rat.poison.App.create(RatPoison.kt:214)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:429)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:377)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        ... 6 more
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
        at java.base/java.lang.Integer.parseInt(Integer.java:668)
        at java.base/java.lang.Integer.parseInt(Integer.java:776)
        at rat.poison.RatPoison.convStrToColor(RatPoison.kt:390)
        at rat.poison.RatPoison.strToColor(RatPoison.kt:378)
        at rat.poison.ui.uiHelpers.VisColorPickerCustom.update(VisColorPickerCustom.kt:42)
        at rat.poison.ui.uiHelpers.VisColorPickerCustom.<init>(VisColorPickerCustom.kt:23)
        at rat.poison.ui.tabs.visualstabs.ChamsEspTab.<init>(ChamsEspTab.kt:23)
        at rat.poison.ui.tabs.VisualsTabKt.<clinit>(VisualsTab.kt:21)
        ... 14 more

**Comment by italycross** [comment]
I repaired it by download and set it up from zero, it had to be some settings problem
