### ISSUE TITLE
Repeated crashing, unknown cause

### ISSUE THREAD

**Issue by Zayoe4** [TheFuckingRat/RatPoison#191]
Exception in thread "DefaultDispatcher-worker-1" java.lang.IndexOutOfBoundsException: Bounds exceeds available space : size=21116, offset=21176
        at com.sun.jna.Memory.boundsCheck(Memory.java:220)
        at com.sun.jna.Memory.getInt(Memory.java:484)
        at rat.poison.game.entity.PlayerKt.nearestBone(Player.kt:147)
        at rat.poison.scripts.aim.GeneralKt.findTarget(General.kt:60)
        at rat.poison.scripts.aim.GeneralKt.findTarget$default(General.kt:27)
        at rat.poison.scripts.esp.GlowESP.GlowESPAppKt$glowEspApp$1.invoke(GlowESPApp.kt:23)
        at rat.poison.scripts.esp.GlowESP.GlowESPAppKt$glowEspApp$1.invoke(GlowESPApp.kt)
        at rat.poison.App.render(RatPoison.kt:276)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:125)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by TheFuckingRat** [comment]
Should be fixed,reopen/new issue if not...
