### ISSUE TITLE
Ratpoison 1.5.3 crashes when scanning for players on new update.

### ISSUE THREAD

**Issue by spy12085621** [TheFuckingRat/RatPoison#226]
May be due to the new models. Crashes not on injection or matchmaking, but when scanning players, if I were to guess.

**Comment by Zayoe4** [comment]
Do you have box esp enabled?

**Comment by spy12085621** [comment]
> Do you have box esp enabled?

Yeah, I do mainly use Box ESP. The thing is, though, Box ESP doesn't even appear before crashing, I bet it crashes the moment it tries to scan for a player..

**Comment by spy12085621** [comment]
---
Exception in thread "DefaultDispatcher-worker-1" java.lang.IndexOutOfBoundsException: Bounds exceeds available space : size=45892, offset=45932
        at com.sun.jna.Memory.boundsCheck(Memory.java:220)
        at com.sun.jna.Memory.getInt(Memory.java:484)
        at rat.poison.game.entity.PlayerKt.armor(Player.kt:60)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt:89)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt)
        at rat.poison.App.render(RatPoison.kt:287)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:125)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
---

It even crashes with bots. Sorry if this looks like spam

**Comment by Trigmam** [comment]
Same exact thing happens to me probably isn't working because of the new csgo update

**Comment by Zayoe4** [comment]
Here's how to fix it:

1. Open your settings folder.
2. Find your BoxEsp.txt file
3. Right Click on BoxEsp.txt then click "Edit"
4. Change `ENABLE_BOX_ESP = true` to `ENABLE_BOX_ESP = false`

This only let's you turn off box esp so you can use the rest of the program. @TheFuckingRat  still needs to patch the bug.

**Comment by Trigmam** [comment]
Thanks 🙏

**Comment by matzyr** [comment]
Glow ESP works normally btw

**Comment by Trigmam** [comment]
Yeah thankfully
