### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by Frappyy** [TheFuckingRat/RatPoison#231]
Hi,

So I just recently started using this cheat (love it already) and I hopped on a aim training map to test it out. There's a problem however, after running the cheat, everything is fine but after 5-10 seconds the ESP dissappears and I get the "java.lang.OutOfMemoryError: Cannot allocate 4032 bytes" error in the RatPoison console. This happened after I enabled SkeletonESP. Any way to fix this? Thanks!

Console output:
```
Loading settings...
Settings loaded
Launching...
App Title: Counter-Strike: Global Offensive
Waiting for App
Initializing overlay
Exception in thread "DefaultDispatcher-worker-1" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.OutOfMemoryError: Cannot allocate 4032 bytes
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:124)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
Caused by: java.lang.OutOfMemoryError: Cannot allocate 4032 bytes
        at com.sun.jna.Memory.<init>(Memory.java:115)
        at rat.poison.scripts.esp.SkeletonESPKt$drawBone$boneMemory$2.invoke(SkeletonESP.kt:102)
        at rat.poison.scripts.esp.SkeletonESPKt$drawBone$boneMemory$2.invoke(SkeletonESP.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at rat.poison.scripts.esp.SkeletonESPKt.drawBone(SkeletonESP.kt:105)
        at rat.poison.scripts.esp.SkeletonESPKt.access$drawBone(SkeletonESP.kt:1)
        at rat.poison.scripts.esp.SkeletonESPKt$skeletonEsp$1.invoke(SkeletonESP.kt:66)
        at rat.poison.scripts.esp.SkeletonESPKt$skeletonEsp$1.invoke(SkeletonESP.kt)
        at rat.poison.App.render(RatPoison.kt:290)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        ... 6 more
```

**Comment by TheFuckingRat** [comment]
Try editting the .bat file (right click, edit with notepad), and set the -Xmx/-Xms parameters higher. See [here](http://www.tracemodeler.com/manual/topics/general-increase-the-available-memory.html)

**Comment by Frappyy** [comment]
> Try editting the .bat file (right click, edit with notepad), and set the -Xmx/-Xms parameters higher. See [here](http://www.tracemodeler.com/manual/topics/general-increase-the-available-memory.html), most likely running low on available/usable memory.

Thanks! That fixed it.
