### ISSUE TITLE
Critical error, I'd say. Stops the hack from working entirely.

### ISSUE THREAD

**Issue by InSovietCS** [TheFuckingRat/RatPoison#263]
This is the error that is spewed out:

        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Exception in thread "DefaultDispatcher-worker-2" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.ExceptionInInitializerError
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:124)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
Caused by: java.lang.ExceptionInInitializerError
        at rat.poison.ui.UIMenu.<init>(UIMenu.kt:46)
        at rat.poison.App.create(RatPoison.kt:228)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:429)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:377)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        ... 6 more
Caused by: java.lang.NumberFormatException: empty String
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
        at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.base/java.lang.Float.parseFloat(Float.java:461)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisSlider.update(ATabVisSlider.kt:44)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisSlider.<init>(ATabVisSlider.kt:26)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisSlider.<init>(ATabVisSlider.kt:13)
        at rat.poison.ui.uiHelpers.tables.AimBTrigTable.<init>(AimBTrigTable.kt:23)
        at rat.poison.ui.tabs.AimTab.<init>(AimTab.kt:24)
        at rat.poison.ui.UIMenuKt.<clinit>(UIMenu.kt:13)
        ... 12 more

When launched without admin it says that java is not a recognized command.
Time of use: 3 days in a row by launching as admin with no issues.

Please help :(

OS is windows 10 ofc
Restarting PC, Steam and CS doesn't help.

**Comment by PatreskoCZ** [comment]
Hey <3

You use "Start RatPosion 1.5.3.3" right?
Try open only "RatPosion 1.5.3.3" in CSGO. Wait 5-10 second and cheat must start automatic.

**Comment by InSovietCS** [comment]
That... didn't work unfortunately. HOWEVER what did work was to reinstall everything and rebuild the cheat. However, this error appears a couple of sessions after (in the variant of worker 1 or 2) and it says bad logic (precisely the reason I slapped the issue here).

**Comment by InSovietCS** [comment]
UPDATE: Yeah it's back and it isn't f*cing off this time...

**Comment by TheFuckingRat** [comment]
Error says a bone trigger fov value is empty in one of your categories. Will push a fix soon that will catch it instead of crashing
