### ISSUE TITLE
Built, but can't run.

### ISSUE THREAD

**Issue by ghost** [TheFuckingRat/RatPoison#265]
Exception in thread "DefaultDispatcher-worker-1" java.lang.UnsatisfiedLinkError: C:\Users\USER\AppData\Local\Temp\lwjgl??\3.2.1-SNAPSHOT\lwjgl.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at org.lwjgl.system.Library.loadSystem(Library.java:162)
        at org.lwjgl.system.Library.loadSystem(Library.java:152)
        at org.lwjgl.system.Library.loadSystem(Library.java:116)
        at org.lwjgl.system.Library.loadSystem(Library.java:67)
        at org.lwjgl.system.Library.<clinit>(Library.java:50)
        at org.lwjgl.system.MemoryAccessJNI.<clinit>(MemoryAccessJNI.java:13)
        at org.lwjgl.system.Pointer.<clinit>(Pointer.java:28)
        at org.lwjgl.system.Platform.mapLibraryNameBundled(Platform.java:80)
        at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:673)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:122)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by InSovietCS** [comment]
Reinstall JRE 13. Uninstall ALL other Java products. Seems like it cannot find the necessarry files to run the bloody thing. Also set the JAVA HOME directory as well as the bin path (same thing but worked wonders when I had a similar error)

**Comment by Niomeee** [comment]
> Reinstall JDK 13. Uninstall ALL other Java products. Seems like it cannot find the necessarry files to run the bloody thing. Also set the JAVA HOME directory as well as the bin path (same thing but worked wonders when I had a similar error)

Will try reinstalling again, Hope it works this time.

**Comment by Niomeee** [comment]
A little update, doesn't seem to work and i'm really confused.
