### ISSUE TITLE
Problem Launching

### ISSUE THREAD

**Issue by ThiccTomato** [TheFuckingRat/RatPoison#268]
whenever i launch it states 

Exception in thread "DefaultDispatcher-worker-1" java.lang.UnsatisfiedLinkError: C:\Users\Admin\AppData\Local\Temp\lwjgl??????\3.2.1-SNAPSHOT\lwjgl.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2440)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2497)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
        at java.base/java.lang.Runtime.load0(Runtime.java:744)
        at java.base/java.lang.System.load(System.java:1873)
        at org.lwjgl.system.Library.loadSystem(Library.java:162)
        at org.lwjgl.system.Library.loadSystem(Library.java:152)
        at org.lwjgl.system.Library.loadSystem(Library.java:116)
        at org.lwjgl.system.Library.loadSystem(Library.java:67)
        at org.lwjgl.system.Library.<clinit>(Library.java:50)
        at org.lwjgl.system.MemoryAccessJNI.<clinit>(MemoryAccessJNI.java:13)
        at org.lwjgl.system.Pointer.<clinit>(Pointer.java:28)
        at org.lwjgl.system.Platform.mapLibraryNameBundled(Platform.java:80)
        at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:673)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:122)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

the problem might be that i just have the dev kit, but whenever i download the regular version, it automatically tries launching the cheat with that, which doesnt work

**Comment by InSovietCS** [comment]
it says it cannot find the dll you need. go to that directory and add the dll yourself

**Comment by ThiccTomato** [comment]
i do have the dll there, it just doesnt have there libraries
