### ISSUE TITLE
Crash Log

### ISSUE THREAD

**Issue by rattedpojzn** [TheFuckingRat/RatPoison#274]
Exception in thread "DefaultDispatcher-worker-1" java.lang.NullPointerException
        at com.badlogic.gdx.graphics.g2d.BitmapFontCache.addGlyph(BitmapFontCache.java:388)
        at com.badlogic.gdx.graphics.g2d.BitmapFontCache.addToCache(BitmapFontCache.java:379)
        at com.badlogic.gdx.graphics.g2d.BitmapFontCache.addText(BitmapFontCache.java:511)
        at com.badlogic.gdx.graphics.g2d.BitmapFont.draw(BitmapFont.java:233)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt:195)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt)
        at rat.poison.App.render(RatPoison.kt:292)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:124)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

Also, do you maybe keep previous version? I was using 1.5.3 Hotfix 1 and I don't think it ever crashed.

**Comment by InSovietCS** [comment]
While this is a known issue, check your ESP settings and switch them all around offline with bots. It seems that the cause is something that causes bad math in the ESP config.

**Comment by rattedpojzn** [comment]
Yeah I figured it had something to do with ESP, but still wanted to post here in case it makes it easier. Wish I had a backup of a previous version.

**Comment by TheFuckingRat** [comment]
Are you using chams? Its the only one thats caused crashing in previous versions.

**Comment by rattedpojzn** [comment]
Yeah, I use Chams alongside ESPBox all the time.

**Comment by M1XT3NZ** [comment]
[1.5.3.1](https://codeload.github.com/TheFuckingRat/RatPoison/zip/876b8b50b4c0008aee2bdf3c6ff624042af56b24)
