### ISSUE TITLE
overlay and many features not working

### ISSUE THREAD

**Issue by ThiccTomato** [TheFuckingRat/RatPoison#291]
if menu is enabled it doesnt work at all and gives me this error:
Exception in thread "DefaultDispatcher-worker-1" java.lang.UnsatisfiedLinkError: C:\Users\Admin\AppData\Local\Temp\lwjgl??????\3.2.1-SNAPSHOT\lwjgl.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
        at java.base/java.lang.Runtime.load0(Runtime.java:765)
        at java.base/java.lang.System.load(System.java:1834)
        at org.lwjgl.system.Library.loadSystem(Library.java:162)
        at org.lwjgl.system.Library.loadSystem(Library.java:152)
        at org.lwjgl.system.Library.loadSystem(Library.java:116)
        at org.lwjgl.system.Library.loadSystem(Library.java:67)
        at org.lwjgl.system.Library.<clinit>(Library.java:50)
        at org.lwjgl.system.MemoryAccessJNI.<clinit>(MemoryAccessJNI.java:13)
        at org.lwjgl.system.Pointer.<clinit>(Pointer.java:28)
        at org.lwjgl.system.Platform.mapLibraryNameBundled(Platform.java:80)
        at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:673)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:123)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
and when the menu is disabled, many features like the bomb timer (which gives the same error) the bone esp, the box esp and the hitmarker wont work

**Comment by TheFuckingRat** [comment]
Make sure java_home and path are set correctly, try having the build.bat install the jdk for you and see if that helps

**Comment by ThiccTomato** [comment]
the java home and path were set correctly and when i deinstalled java and tried to let the build.bat install it it just said i should set my java_home pah correctly, which of course doesnt work if i dont have java installed

**Comment by matt1tk** [comment]
The install script will download and install the JDK. What do you mean it says you need to set the java home variable? It does that automatically.

**Comment by ThiccTomato** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/60012472/73670255-302e9d00-46a9-11ea-957b-4f08b432460a.png)
heres what it says

**Comment by matt1tk** [comment]
So run the install script again and say “yes” to installing the JDK

**Comment by ThiccTomato** [comment]
i dont understand what you mean with the "install script". if you mean the build.bat, then this (the picture posted before) is the only thing i get. no option to install the jdk

**Comment by russianhorror** [comment]
@ThiccTomato , download the **latest updates (v. 1.5.5)** by downloading directly as a ZIP.
run "build.bat" and you will see " **Install JDK (required)? [Y/N]** " type Y and press enter. 

Automatically install JDK and setting JAVA_HOME variable available only from latest version.

**Comment by ThiccTomato** [comment]
The JDK is now installed and i built it again, but it still doesnt work

**Comment by Zayoe4** [comment]
You have to delete your build file before you build it again

**Comment by ThiccTomato** [comment]
i cant delete the build file because then i wouldnt be able to build it again, and i have already deleted the build. the jdk was only installed because i downloaded a newer version of ratpoison.

**Comment by russianhorror** [comment]
Try to install in a different folder, unzip RatPoison-master to new folder
(like "RatPoison 1-5-5", and run build.bat , if you install JDK before -
type N when script ask u about it. 🤔

вт, 4 февр. 2020 г. в 16:00, ᴇʀɪᴄ sᴄʜᴍᴇʀBᴀᴄʜ <notifications@github.com>:

**Comment by ThiccTomato** [comment]
still didnt work. i suppose its a problem with java

**Comment by TheFuckingRat** [comment]
This is a specific issue that everyone else has been able to solve, on a fresh windows 10 it works fine, this has also been addressed several times in other issues, if those don't help theres nothing more we can do to help.
