### ISSUE TITLE
Crash constantly liike twice a game but some  times its like never.

### ISSUE THREAD

**Issue by Usernameistakensad** [TheFuckingRat/RatPoison#301]
Exception in thread "DefaultDispatcher-worker-2" java.lang.NullPointerException
        at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:144)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt:180)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt)
        at rat.poison.App.render(RatPoison.kt:297)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:125)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

My Settings are "PM ME ON DISCORD AT MrSquid#8277".

**Comment by TheFuckingRat** [comment]
Will look into it again

**Comment by Zayoe4** [comment]
It's related to boxesp im pretty sure

**Comment by Usernameistakensad** [comment]
> It's related to boxesp im pretty sure

yea it was forgot to close it ty mate :)

**Comment by Zayoe4** [comment]
@TheFuckingRat  Can you look into the boxesp causing this error?

**Comment by TheFuckingRat** [comment]
@Zayoe4 Is it still an issue? Try the beta version 1.6..

**Comment by TheFuckingRat** [comment]
Should be fixed in the latest 1.6 update
