### ISSUE TITLE
RatPoison throws out a lot of errors and only AimBot works sometimes

### ISSUE THREAD

**Issue by Hypernova2** [TheFuckingRat/RatPoison#304]
After i startup RatPoison, like not the installer, but the actual hack, after awhile it throws a lot of errors in the cmd, and actually in-game, i don't think anything works with ESP on, and AimBot sometimes works without it. I think the issue isn't with the software but with my graphics card, that doesn't support something like shaders? And the error codes are here below:

Loading settings...
Settings loaded
Launching...
App Title: Counter-Strike: Global Offensive
Exception in thread "DefaultDispatcher-worker-2" java.lang.IllegalArgumentException: Error compiling shader: Vertex shader
Vertex shader failed to compile with the following errors:
ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated

Fragment shader:
Fragment shader failed to compile with the following errors:
ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated

        at com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteBatch.java:163)
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:126)
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:80)
        at com.badlogic.gdx.scenes.scene2d.Stage.<init>(Stage.java:92)
        at rat.poison.App.create(RatPoison.kt:226)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:429)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:377)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:125)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by TheFuckingRat** [comment]
This is an issue with outdated drivers/older graphics cards not supporting ogl3, haven't found an allternative to use 2 at the moment.

**Comment by TheProfessorJJ** [comment]
is there any fix to this?
