### ISSUE TITLE
Raise of NumberFormatException caused by BoneTrigger when Taser is used.

### ISSUE THREAD

**Issue by x7airworker** [TheFuckingRat/RatPoison#310]
When the BoneTrigger is enabled and you have a Taser in the hand a NumberFormatException is thrown.
```
java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:592)
at java.lang.Integer.parseInt(Integer.java:615)
at rat.poison.scripts.BoneTriggerKt$boneTrigger$$inlined$every$1.invoke(Every.kt:52)
at rat.poison.scripts.BoneTriggerKt$boneTrigger$$inlined$every$1.invoke(Every.kt)
at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)```

**Comment by TheFuckingRat** [comment]
Will be fixed in the next update
