### ISSUE TITLE
Problem building RatPoison

### ISSUE THREAD

**Issue by s1lmaris** [TheFuckingRat/RatPoison#380]
```
Building RatPoison...
Could not unzip C:\Users\MAT\.gradle\wrapper\dists\gradle-4.10.3-all\81msde2dx9p4vji0mjgtvxkcb\gradle-4.10.3-all.zip to C:\Users\MAT\.gradle\wrapper\dists\gradle-4.10.3-all\81msde2dx9p4vji0mjgtvxkcb.
Reason: error in opening zip file
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at org.gradle.wrapper.Install.unzip(Install.java:218)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:75)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```
When I exec as admin I get this:

```
Building RatPoison...
"gradlew" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
```

Same problem with both 1.5.1 and 1.6 versions. I have latest JDK and JRE installed. Any advice?

**Comment by matt1tk** [comment]
Strange issue, try just manually downloading and running http://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13.0.2%2B8/OpenJDK13U-jdk_x64_windows_hotspot_13.0.2_8.msi 

then type N to the build.bat when it asks whether you want to install the JDK
