### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by cristyanul** [TheFuckingRat/RatPoison#426]
Game does not crash. Only the cheat crashes.
`Exception in thread "DefaultDispatcher-worker-1" java.lang.IllegalStateException: Call end() before beginning a new shape batch.
        at com.badlogic.gdx.graphics.glutils.ShapeRenderer.begin(ShapeRenderer.java:206)
        at com.badlogic.gdx.graphics.glutils.ShapeRenderer.begin(ShapeRenderer.java:199)
        at rat.poison.scripts.BombTimerKt$bombTimer$1.invoke(BombTimer.kt:43)
        at rat.poison.scripts.BombTimerKt$bombTimer$1.invoke(BombTimer.kt)
        at rat.poison.App.render(RatPoison.kt:339)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:153)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)`

**Comment by retart1337** [comment]
Was fixed in newest versions
