### ISSUE TITLE
Works in main menu but stops working once DZ loads. Error below

### ISSUE THREAD

**Issue by Runtg** [TheFuckingRat/RatPoison#447]
Loading settings...
Settings loaded
Launching...
App Title: Counter-Strike: Global Offensive
Waiting for App
Initializing overlay
Overlay initialized
Exception in thread "DefaultDispatcher-worker-1" java.lang.IndexOutOfBoundsException: Bounds exceeds available space : size=45932, offset=45948
        at com.sun.jna.Memory.boundsCheck(Memory.java:220)
        at com.sun.jna.Memory.getInt(Memory.java:484)
        at rat.poison.game.entity.PlayerKt.armor(Player.kt:66)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt:119)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt)
        at rat.poison.App.render(RatPoison.kt:407)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:195)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by Runtg** [comment]
nvm fixed by updating.
