### ISSUE TITLE
Error using box ESP

### ISSUE THREAD

**Issue by douglask1125** [TheFuckingRat/RatPoison#451]
This happens when I load in a game while using box ESP, new update probably broke it

Exception in thread "DefaultDispatcher-worker-1" java.lang.IndexOutOfBoundsException: Bounds exceeds available space : size=45932, offset=45948
        at com.sun.jna.Memory.boundsCheck(Memory.java:220)
        at com.sun.jna.Memory.getInt(Memory.java:484)
        at rat.poison.game.entity.PlayerKt.armor(Player.kt:64)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt:110)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt)
        at rat.poison.App.render(RatPoison.kt:339)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:153)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
![image](https://user-images.githubusercontent.com/66835881/84512780-aba4f880-acf2-11ea-96ae-41de135817b3.png)

**Comment by sotakoira** [comment]
yeah, download newest beta and build that

**Comment by douglask1125** [comment]
ok will try

**Comment by douglask1125** [comment]
Ok things seem to be working fine (game did crash several times but I doubt it's the cheat

console still shows an error tho
![image](https://user-images.githubusercontent.com/66835881/84563326-d475ce00-ad84-11ea-99cb-8d3a01c75af7.png)

**Comment by douglask1125** [comment]
Yeah it's an error, box sometimes doesnt show up

**Comment by matt1tk** [comment]
I get the same but ratpoison still works. closing for now
